### ISSUE TITLE
pip3 install minimagen fails

### ISSUE THREAD

**Issue by tavdog** [AssemblyAI-Examples/MinImagen#1]
Getting this error when trying to install with pip3 on macOS
 from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      
I tried installing setuptools, upgrading pip, lots of stuff. no luck.

**Comment by oconnoob** [comment]
@tavdog sorry for the late reply - I didn't get a notification for this. Can you try running
```
sudo apt-get install python3-setuptools
```
and seeing if that helps?

**Comment by tavdog** [comment]
MacOS doest have apt

**Comment by oconnoob** [comment]
@tavdog It looks like this stackoverflow thread might have the answer you're looking for

https://stackoverflow.com/questions/26032836/how-to-install-setuptools-in-mac

**Comment by tavdog** [comment]
Fixed by installing in venv and also installing following 
brew install cmake
brew install gperftools
brew install pkg-config
