### ISSUE TITLE
Training params

### ISSUE THREAD

**Issue by AndrewBaker** [AssemblyAI-Examples/MinImagen#2]
Thanks for the article.

When I remove --TESTING param it looks like training would take a year.
This is running on Collab/T4 gpu.

Are there any params I can use to train in a reasonable amount of time, and see output images that don't look like static?

Thanks

**Comment by oconnoob** [comment]
Hey there @AndrewBaker - training indeed does take a while, I stripped off many of the bells and whistles discovered/invented over the last couple of years in making diffusion models more efficient. We trained for a while and did get _some_ results, but given that the implementation is minimal they were not great. If you'd like I may be able to drop the checkpoint for you to use, but maybe using something like Stable Diffusion would be better for your goals? It's open source and weights are available. We have a guide on [how to run stable diffusion](https://www.assemblyai.com/blog/how-to-run-stable-diffusion-locally-to-generate-images/) - you can get up-and-running in ~5-10 minutes.

![image_0](https://user-images.githubusercontent.com/46252299/186693678-06f033a5-878c-4b81-b10b-c2213fbcc735.png)
