### ISSUE TITLE
The link of the checkpoint v1.4 has expired

### ISSUE THREAD

**Issue by night3759** [AssemblyAI-Examples/MinImagen#5]
I was trying to download the weights, but its link has expired. Is there any new link to download the weights. I can't waiting to experience   this model. Thank you very much.

**Comment by oconnoob** [comment]
Hi @night3759 - I think you might be thinking of the Stable Diffusion model? That has v1.4 weights that you can find [here](https://www.assemblyai.com/blog/how-to-run-stable-diffusion-locally-to-generate-images/#step-5-download-stable-diffusion-weights)
